global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mlops_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['serve:8000']
      
  - job_name: 'workflow_pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

