name: CD

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'dockerfile'
      - 'requirements.txt'
      - 'docker-compose.yml'
      - 'scripts/**'
      - 'workflow.py'
      - '.github/workflows/cd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "CI/CD Deployment" \
            --parameters 'commands=[
              "sudo -i -u ec2-user bash -c \"
                cd /home/ec2-user/mlops-serve &&
                git fetch --all &&
                git reset --hard origin/main &&
                docker compose down -v || true &&
                docker rm -f grafana prometheus pushgateway mlops-serve || true &&
                docker compose up --build -d &&
                docker image prune -a -f
              \""
            ]' \
            --timeout-seconds 600 \
            --output text

  
