name: CD

on:
  push:
    branches:
      - main
    paths:
        - 'app/**'
        - 'dockerfile'
        - 'requirements.txt'
        - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Upload and deploy on EC2
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/mlops-serve
            git pull
            docker compose down
            docker compose up --build -d
